// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zeus.Academia.Features.ReferenceData.ManageDegrees.Shared;

#nullable disable

namespace Zeus.Academia.Features.ReferenceData.ManageDegrees.Shared.Migrations
{
    [DbContext(typeof(ManageDegreesDbContext))]
    [Migration("20260929172158_ManageDegreesInitial")]
    partial class ManageDegreesInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zeus.Academia.Features.ReferenceData.ManageDegrees.Shared.DegreeRecord", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Code");

                    b.ToTable("Degrees", null, t =>
                        {
                            t.HasCheckConstraint("CK_Degrees_Code_Allowed", "[Code] IN ('BSC', 'MCS', 'PHD')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
