// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zeus.Academia.Features.SharedKernel.Foundation.Persistence;

#nullable disable

namespace Zeus.Academia.Features.SharedKernel.Foundation.Persistence.Migrations
{
    [DbContext(typeof(SharedKernelDbContext))]
    [Migration("20260929034526_SharedKernelInitial")]
    partial class SharedKernelInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zeus.Academia.Features.SharedKernel.Foundation.Domain.Academic", b =>
                {
                    b.Property<string>("EmpNr")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateOnly?>("ContractEndDate")
                        .HasColumnType("date");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsTenured")
                        .HasColumnType("bit");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("EmpNr");

                    b.ToTable("Academics", null, t =>
                        {
                            t.HasCheckConstraint("CK_Academics_EmpNrLength", "LEN([EmpNr]) = 6");

                            t.HasCheckConstraint("CK_Academics_EmploymentMutualExclusion", "NOT ([IsTenured] = 1 AND [ContractEndDate] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Zeus.Academia.Features.SharedKernel.Foundation.Domain.AcademicQualification", b =>
                {
                    b.Property<string>("EmpNr")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("DegreeCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UniversityCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmpNr", "DegreeCode");

                    b.ToTable("AcademicQualifications", (string)null);
                });

            modelBuilder.Entity("Zeus.Academia.Features.SharedKernel.Foundation.Domain.AcademicQualification", b =>
                {
                    b.HasOne("Zeus.Academia.Features.SharedKernel.Foundation.Domain.Academic", null)
                        .WithMany("Qualifications")
                        .HasForeignKey("EmpNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zeus.Academia.Features.SharedKernel.Foundation.Domain.Academic", b =>
                {
                    b.Navigation("Qualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
