// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zeus.Academia.Features.SharedKernel.Foundation.Persistence;

#nullable disable

namespace Zeus.Academia.Features.SharedKernel.Foundation.Persistence.Migrations
{
    [DbContext(typeof(SharedKernelDbContext))]
    [Migration("20260730190855_InitialSharedKernel")]
    partial class InitialSharedKernel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zeus.Academia.Features.SharedKernel.Foundation.Domain.Academic", b =>
                {
                    b.Property<string>("EmpNr")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("ContractEndDate")
                        .HasColumnType("date");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsTenured")
                        .HasColumnType("bit");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("EmpNr");

                    b.ToTable("Academics", null, t =>
                        {
                            t.HasCheckConstraint("CK_Academics_EmploymentMutualExclusion", "NOT ([IsTenured] = 1 AND [ContractEndDate] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Zeus.Academia.Features.SharedKernel.Foundation.Domain.AcademicQualification", b =>
                {
                    b.Property<string>("EmpNr")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .IsFixedLength();

                    b.Property<string>("DegreeCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("UniversityCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("EmpNr", "DegreeCode");

                    b.HasIndex("DegreeCode");

                    b.HasIndex("UniversityCode");

                    b.ToTable("AcademicQualifications", (string)null);
                });

            modelBuilder.Entity("Zeus.Academia.Features.SharedKernel.Foundation.Domain.Degree", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Code");

                    b.ToTable("Degrees", (string)null);
                });

            modelBuilder.Entity("Zeus.Academia.Features.SharedKernel.Foundation.Domain.Extension", b =>
                {
                    b.Property<decimal>("Number")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,0)");

                    b.Property<string>("AssignedEmpNr")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .IsFixedLength();

                    b.HasKey("Number");

                    b.HasIndex("AssignedEmpNr")
                        .IsUnique()
                        .HasDatabaseName("UX_Extensions_AssignedEmpNr")
                        .HasFilter("[AssignedEmpNr] IS NOT NULL");

                    b.ToTable("Extensions", (string)null);
                });

            modelBuilder.Entity("Zeus.Academia.Features.SharedKernel.Foundation.Domain.University", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Code");

                    b.ToTable("Universities", (string)null);
                });

            modelBuilder.Entity("Zeus.Academia.Features.SharedKernel.Foundation.Domain.AcademicQualification", b =>
                {
                    b.HasOne("Zeus.Academia.Features.SharedKernel.Foundation.Domain.Degree", "Degree")
                        .WithMany()
                        .HasForeignKey("DegreeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zeus.Academia.Features.SharedKernel.Foundation.Domain.Academic", "Academic")
                        .WithMany("Qualifications")
                        .HasForeignKey("EmpNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zeus.Academia.Features.SharedKernel.Foundation.Domain.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Academic");

                    b.Navigation("Degree");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Zeus.Academia.Features.SharedKernel.Foundation.Domain.Extension", b =>
                {
                    b.HasOne("Zeus.Academia.Features.SharedKernel.Foundation.Domain.Academic", "AssignedAcademic")
                        .WithOne()
                        .HasForeignKey("Zeus.Academia.Features.SharedKernel.Foundation.Domain.Extension", "AssignedEmpNr")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedAcademic");
                });

            modelBuilder.Entity("Zeus.Academia.Features.SharedKernel.Foundation.Domain.Academic", b =>
                {
                    b.Navigation("Qualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
