// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zeus.Academia.Features.ReferenceData.ManageRanks.Persistence;

#nullable disable

namespace Zeus.Academia.Features.ReferenceData.ManageRanks.Persistence.Migrations
{
  [DbContext(typeof(ManageRanksDbContext))]
  partial class ManageRanksDbContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "8.0.8")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

      modelBuilder.Entity("Zeus.Academia.Features.ReferenceData.ManageRanks.Persistence.RankReference", b =>
          {
            b.Property<string>("Code")
                      .HasMaxLength(16)
                      .HasColumnType("nvarchar(16)");

            b.HasKey("Code");

            b.ToTable("Ranks", (string)null, t =>
                      {
                    t.HasCheckConstraint("CK_Ranks_Code_Allowed", "[Code] IN ('L', 'P', 'SL')");
                  });
          });
#pragma warning restore 612, 618
    }
  }
}
