// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zeus.Academia.Persistence;

#nullable disable

namespace Zeus.Academia.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528051032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zeus.Academia.SharedKernel.Domain.Aggregates.Academic", b =>
                {
                    b.Property<string>("EmpNr")
                        .HasMaxLength(6)
                        .HasColumnType("char(6)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("ContractEndDate")
                        .HasColumnType("date");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("ExtensionExtNr")
                        .HasColumnType("decimal(10,4)");

                    b.Property<bool?>("IsTenured")
                        .HasColumnType("bit");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("EmpNr");

                    b.HasIndex("ExtensionExtNr")
                        .IsUnique()
                        .HasDatabaseName("UX_Academics_ExtensionExtNr")
                        .HasFilter("[ExtensionExtNr] IS NOT NULL");

                    b.ToTable("Academics", null, t =>
                        {
                            t.HasCheckConstraint("CK_Academics_XOR_IsTenured_ContractEndDate", "IsTenured IS NULL OR ContractEndDate IS NULL");
                        });
                });

            modelBuilder.Entity("Zeus.Academia.SharedKernel.Domain.Entities.AcademicQualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicEmpNr")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("char(6)")
                        .IsFixedLength();

                    b.Property<string>("DegreeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UniversityCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("AcademicEmpNr", "DegreeCode")
                        .IsUnique()
                        .HasDatabaseName("UX_AcademicQualifications_EmpNr_Degree");

                    b.ToTable("AcademicQualifications", (string)null);
                });

            modelBuilder.Entity("Zeus.Academia.SharedKernel.Domain.ValueObjects.Extension", b =>
                {
                    b.Property<decimal>("ExtNr")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("ExtNr");

                    b.ToTable("Extensions", (string)null);
                });

            modelBuilder.Entity("Zeus.Academia.SharedKernel.Domain.Aggregates.Academic", b =>
                {
                    b.HasOne("Zeus.Academia.SharedKernel.Domain.ValueObjects.Extension", "Extension")
                        .WithOne()
                        .HasForeignKey("Zeus.Academia.SharedKernel.Domain.Aggregates.Academic", "ExtensionExtNr");

                    b.Navigation("Extension");
                });

            modelBuilder.Entity("Zeus.Academia.SharedKernel.Domain.Entities.AcademicQualification", b =>
                {
                    b.HasOne("Zeus.Academia.SharedKernel.Domain.Aggregates.Academic", null)
                        .WithMany("Qualifications")
                        .HasForeignKey("AcademicEmpNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zeus.Academia.SharedKernel.Domain.Aggregates.Academic", b =>
                {
                    b.Navigation("Qualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
