<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Zeus.Academia.Persistence</RootNamespace>
    <AssemblyName>Zeus.Academia.Persistence</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedKernel\Zeus.Academia.SharedKernel.csproj" />
  </ItemGroup>

</Project>
